name: The Everton Project
favicon: null
layout_spectrum: 0.0514
typography_spectrum: 0.31311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#0018ff'
    - '#080808'
    - '#717171'
  brandStrength: 0.19944069418124855
  lightness: 0.24549233936704695
  saturation: 0.7737487053964287
  rhythmicContrast: 0.6683637162204832
purpose: []
