name: The Everton Project
favicon: null
layout_spectrum: 0.2209871558006853
typography_spectrum: 0.06360237649641931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.19944069418124855
  lightness: 0.24549233936704695
  saturation: 0.7737487053964287
  rhythmicContrast: 0.6683637162204832
purpose: []
